# Protosnirk CI setup:
#   - add LLVM package credentials
#   - install LLVM from their apt package
#   - `cargo check`
#   - `cargo test`

# I would like to thank Zig for having a working
# Travis setup with LLVM. It's just following the instructions
# on LLVM's website, but still.

# Zig is an MIT-licensed open-source programming language,
# available at https://github.com/zig-lang/zig

dist: trusty
sudo: required

git:
  depth: 3

language: rust
rust:
  - stable
  - beta

matrix:
  allow_failures:
    - rust:
        - beta
  fast_finish: true

cache:
  - cargo

notifications:
  email: false

before_install:
  - sudo sh -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main" >> /etc/apt/sources.list'
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q

install:
  - sudo apt-get remove -y llvm-*
  - sudo rm -rf /usr/local/*
  - sudo apt-get install -y llvm-6.0 llvm-6.0-dev llvm-6.0-runtime libllvm6.0
  # llvm-sys wants to run `llvm-config`
  - ls /usr/bin/*6*
  - sudo ln -s /usr/bin/llvm-config-6.0 /usr/bin/llvm-config

script:
  - find /usr/bin -name "*llvm*" | sort
  - llvm-config --version
  - cargo check --verbose
  - cargo test --verbose
