# Protosnirk CI setup:
#   - add LLVM package credentials
#   - install LLVM from their apt package
#   - `cargo check`
#   - `cargo test`

# I would like to thank Zig for having a working
# Travis setup with LLVM. It's just following the instructions
# on LLVM's website, but still.

# Zig is an MIT-licensed open-source programming language,
# available at https://github.com/zig-lang/zig

dist: trusty
sudo: false

notifications:
  email: false

git:
  depth: 3

language: rust
rust:
- stable

cache:
- cargo

addons:
  apt:
    packages:
    - llvm-7
    - llvm-7-dev
    - llvm-7-runtime
    - libllvm7
    sources:
    - llvm-toolchain-trusty-7

before_script:
- llvm-config --version

script:
- cargo check --verbose
- cargo test --all --verbose
